#!/bin/bash
#put your configuration variables in this file
#save it without the .sample extension
#make sure it is executable
#printf '%s' "Defining variables... "

#  Azure settings
export AZURE_LOCATION='westeurope'
export AZURE_ORGANIZATION=chrisvandenabbeele  #just the name, not the URL of you azure devops "organization"
export AZURE_ORGANIZATION_URL="https://dev.azure.com/${AZURE_ORGANIZATION}"  #has to be in the format https://dev.azure.com/[NAME_OF_YOUR_ORGANIZATION]
#get a PAT: https://dev.azure.com/chrisvandenabbeele/_usersSettings/tokens -> "person" icon (top right) -> Personal access tokens.
export AZURE_DEVOPS_EXT_PAT='yswjczyk77rd6rplxbsdl2ospg72thv3m2kmov6mmhdrutxvpxda'    #expires 20210205
###OLD###export AZURE_ACCESS_KEY_ID="AKIAXQX6MQ32SQAWGT7G"
###OLD###export AZURE_SECRET_ACCESS_KEY="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"
export AZURE_PROJECT='cloudone14'    #may only contain lowercase, no numbers, no "-", no "_",...

export AZURE_AKS_NODES='2'

###OLD#### Cloud One Container Security (aka Deep Security Smart Check) settings (for pre-runtime scanning)
export DSSC_NAMESPACE='smartcheck' #Namespace to deploy Cloud One Container Security'
export DSSC_AC='AP-S6QS-QGV5A-DERMB-D9DJ4-H4RN3-MPQSH'
export DSSC_USERNAME='administrator'
export DSSC_TEMPPW='trendmicro'   #this temporarily password will be overwritten by the DSSC_PASSWORD, but it must be defined and it must be different from the DSSC_PASSWORD
export DSSC_PASSWORD='Tr3ndm1cr0!'
export DSSC_HOST='will be generated by this script'
export DSSC_REGUSER='administrator'
export DSSC_REGPASSWORD='Tr3ndm1cr0!'

###OLD#### Cloud One Application Security settings (for runtime protection)
export TREND_AP_KEY='c630c28f-854e-415d-918e-a2f21aa25c0b'
export TREND_AP_SECRET='af0995db-19c8-4f12-85ed-a7255f9baffc'

###OLD#### APPS
###OLD#### using distinct variables as exporting arrays in bash is still troublesome
APP_GIT_URL1='https://github.com/cvdabbeele/c1-app-sec-moneyx.git'
APP_GIT_URL2='https://github.com/cvdabbeele/troopers.git'
APP_GIT_URL3='https://github.com/cvdabbeele/mydvwa.git'

#----------do not edit below this line--------------------------
# Generating names for Apps, Stack, Pipelines, ECR, CodeCommit repo,..."
#generate the names of the apps from the git URL
export APP1=`echo ${APP_GIT_URL1} | awk -F"/" '{print $NF}' | awk -F"." '{ print $1 }' | tr -cd '[:alnum:]'| awk '{ print tolower($1) }'`
export APP2=`echo ${APP_GIT_URL2} | awk -F"/" '{print $NF}' | awk -F"." '{ print $1 }' | tr -cd '[:alnum:]'| awk '{ print tolower($1) }'`
export APP3=`echo ${APP_GIT_URL3} | awk -F"/" '{print $NF}' | awk -F"." '{ print $1 }' | tr -cd '[:alnum:]'| awk '{ print tolower($1) }'`

export AZURE_NROFNODES="3"

# set default location
az configure --defaults location=$AZURE_LOCATION
