

    # Scan the Container Image with Deep Security Smart Check
    - script: |
        echo 'preparing things'
        openssl s_client -showcerts -connect $(DSSC_HOST):443 < /dev/null | \
          sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $(DSSC_HOST).crt
        sudo cp $(DSSC_HOST).crt /usr/local/share/ca-certificates/$(DSSC_HOST).crt
        sudo mkdir -p /etc/docker/certs.d/$(DSSC_HOST):5000
        sudo cp $(DSSC_HOST).crt /etc/docker/certs.d/$(DSSC_HOST):5000/ca.crt

        sudo update-ca-certificates
        echo 'Sending Image to scanner'
        docker run  -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.cache/:/root/.cache/ deepsecurity/smartcheck-scan-action \
        --preregistry-scan \
        --preregistry-password=$(DSSC_REGPASSWORD) \
        --preregistry-user=$(DSSC_REGUSER) \
        --image-name=$(containerRegistry)/$(imageRepository):$(tag) \
        --smartcheck-host=$(DSSC_HOST) \
        --smartcheck-user=$(DSSC_USERNAME) \
        --smartcheck-password=$(DSSC_PASSWORD) \
        --insecure-skip-tls-verify \
        --insecure-skip-registry-tls-verify \
        --findings-threshold='{"malware": 0, "vulnerabilities": { "defcon1": 0, "critical": 0, "high": 0 }, "contents": { "defcon1": 0, "critical": 0, "high": 0 }, "checklists": { "defcon1": 0, "critical": 0, "high": 0 }}'
      displayName: "Scan pre-registry"

    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - name: Deep Security Smart Check Scan ACR
          # Be sure to specify the latest version of smartcheck-scan-action
          uses: deep-security/smartcheck-scan-action@latest
          with:
            DSSC_IMAGE_NAME: $(containerRegistry)/$(imageRepository):$(tag)
            DSSC_SMARTCHECK_HOST: $(DSSC_HOST)
            DSSC_SMARTCHECK_USER: $(DSSC_USERNAME)
            DSSC_SMARTCHECK_PASSWORD: $(DSSC_PASSWORD)
            DSSC_IMAGE_PULL_AUTH: '{"username": "$(SP_APP_ID)","password": "$(SP_PASSWD)"}'
            DSSC_FINDINGS_THRESHOLD: '{"malware": 0, "vulnerabilities": { "defcon1": 0, "critical": 0, "high": 0 }, "contents": { "defcon1": 0, "critical": 0, "high": 0 }, "checklists": { "defcon1": 0, "critical": 0, "high": 0 }}'            
            DSSC_INSECURE_SKIP_TLS_VERIFY: true
            DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true

    #Infor: login to ACR
    #docker login c1appsecmoneyx.azurecr.io  -u $SP_APP_ID -p $SP_PASSWD

    # To Do: use "exit 1"  to stop the pipeline
    # end of Scan the Container Image with Deep Security Smart Check



